### ISSUE TITLE
M65N not correctly detected in scan_system.sh

### ISSUE THREAD

**Issue by KonradJPE** [MEN-Mikro-Elektronik/13MD05-90#179]
**1.** Add proper detection of M65N in scan_system.sh.
Differences between scan_system.sh and mdiswiz (system.dsc file): 
scan_system.sh:

- m65_x is added. 

mdiswiz:

- m65_xa and m65_xb with SUBDEVICE_OFFSET=0x00/0x80 parameter is added

**2.** While performing icanl2_veri there are errors in 2 tests:
```
j - Remote transmit frames
k - Cyclic Tx/Timestamping
```
Should we investigate these "j,k" errors?

**Comment by dpfeuffer** [comment]
To 2.
Is the M65 plugged stand alone on an M-Module carrier? There is an errata about GND problems:
20m065-er.pdf (I added the document to InStep Customer\User Manuals).
Excerpt:
1.2.1 Description
There  are  ground  bounce  effects  on  the  connection  between  M-Module  and  carrier
board because of insufficient GND pins.
1.2.2 Projected Impact
In rare cases, errors occur when an another M-Module is plugged next to an M65 M-
Module on the same F205 carrier board.
1.2.3 Workarounds
Plug the M65 M-Module on a single-mezzanine carrier board, e.g., F204.

**Comment by KonradJPE** [comment]
> 1.2.3 Workarounds
> Plug the M65 M-Module on a single-mezzanine carrier board, e.g., F204.

M65 M-Module is plugged into G204.

**Comment by KonradJPE** [comment]
1. Fixed,
2. Moved to issue: https://github.com/MEN-Mikro-Elektronik/13MD05-90/issues/181
