### ISSUE TITLE
mdiswizard formatting error / font not supported

### ISSUE THREAD

**Issue by HIttner** [MEN-Mikro-Elektronik/13MD05-90#44]
I tested the latest commit in Lubuntu 18.04 and the mdis wizard opens with messed up text lines (see screenshot for kernel version and picture of behavior)

![2018-09-14-171219_1280x1024_scrot](https://user-images.githubusercontent.com/43148084/45559109-e0e09600-b841-11e8-8e15-0560a0405b70.png)

when I try to create a project using scan_system.sh instead it fails too because gksu is not supported anymore in Lubuntu 18.04
![gksu](https://user-images.githubusercontent.com/43148084/45560223-ceb42700-b844-11e8-8e89-f0ce121e0b18.JPG)
![grafik](https://user-images.githubusercontent.com/43148084/45560470-76315980-b845-11e8-8238-17b89171493d.png)

**Comment by mlassota** [comment]
Fixed

**Comment by mlassota** [comment]
It turned out that 'pkexec' is not a good replacement for 'gksudo' as it does change user directory to root directory if not configured. And it's hard to expect from user to have it configured earlier as it requires to create configuration file for each application that needs privilege escalation - this is pkexec policy. We could try to make it change directory back to user directory,  but it would require a couple of code lines in the script and would obfuscate readability.
Therefore usage of gksudo and pkexec has been removed.
If a user wants to use scanner in MDIS Wizard he needs to run wizard with 'sudo', otherwise there will be a proper message in scanner that it needs to be run with said 'sudo'.
