### ISSUE TITLE
WINDOWS directory with mdiswiz.exe.

### ISSUE THREAD

**Issue by KonradJPE** [MEN-Mikro-Elektronik/13MD05-90#96]
Should WINDOWS directory be removed from MDIS repo (13MD05-90/MDISForLinux/WINDOWS)? 
It contains mdiswiz executable for Windows.

**Comment by dpfeuffer** [comment]
I'm not able to decide it. I will discuss it with Florian and Thomas Schnürer today as soon as possible. Then I will give you feedback.

**Comment by dpfeuffer** [comment]
Thomas told me, that mdiswiz.exe makes only sense for ElinOs Windows build hosts and it was used in the past only from one customer. And we will skip ElinOs support, as far as I know.
So, please remove it!
Your question comes just in time because I'm rewriting the MDIS User Manual for Linux. :-) I will remove the description of the existence of the Windows folder in the User Manual now.

**Comment by KonradJPE** [comment]
Thanks for your answer. This directory will be removed from the next release - 13MD05-90_02_01.

**Comment by dpfeuffer** [comment]
Is it possible, to remove it from 13MD05-90_02_00_b2?

**Comment by dpfeuffer** [comment]
Ok, my request comes too late ;-) No problem, you can do this for the next release 13MD05-90_02_01.
